batch_size: 128
hid_dim: 128
lr: 0.003
wd: !!float 1e-4
n_layers: 2
dropout: [0.2, 0.1]
device: "cpu"
early_stopping: 10
n_fold: 5
seed: 2023
max_epochs: 10
gated: True
dataset: S-FFSD
test_size: 0.4

